name: hasta_takip
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: '>=3.2.3 <4.0.0'
dependencies:
  connectivity_plus: ^5.0.2
  cupertino_icons: ^1.0.2
  dio: ^5.4.0
  easy_localization: ^3.0.3
  equatable: ^2.0.5
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.4
  flutter_screenutil: ^5.9.0
  flutter_secure_storage: ^9.0.0
  flutter_svg: ^2.0.9
  fpdart: ^1.1.0
  freezed_annotation: ^2.4.1
  go_router: ^12.1.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  intl: ^0.19.0
  json_annotation: ^4.8.1
  shared_preferences: ^2.2.2
  smooth_page_indicator: ^1.1.0
  url_launcher: ^6.2.2
  audioplayers: any
  wakelock_plus: ^1.1.3
  sensors_plus: ^4.0.1
  camera: ^0.9.4+3
  video_player: ^2.7.0
  image_picker: ^0.8.4+2
  gallery_saver: ^2.3.2
  firebase_storage: ^11.6.0
  firebase_database: ^10.4.0
  file_picker: ^6.1.1
  firebase_core: ^2.24.2
  firebase_auth: ^4.16.0
  flutter_sms: ^2.3.3
  flutter_pdfview: ^1.3.2
  path_provider: ^2.1.2
  flutter_launcher_icons: ^0.13.1

dev_dependencies:
  build_runner: ^2.4.7
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.4.6
  hive_generator: ^2.0.1
  json_serializable: ^6.7.1
  very_good_analysis: ^5.1.0

flutter:
  uses-material-design: true

  assets:
    - assets/json/
    - assets/translations/
    - assets/audio/
    - assets/pdf/
    - assets/image/

flutter_launcher_icons:
  android: 'launcher_icon'
  ios: true
  remove_alpha_ios: true
  image_path: 'assets/image/logo_light.jpeg'
  min_sdk_android: 21
