/// Flutter icons NyIcons
/// Copyright (C) 2023 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  NyIcons
///      fonts:
///       - asset: fonts/NyIcons.ttf
///
///
///
// ignore_for_file: constant_identifier_names,
// ignore_for_file: use_late_for_private_fields_and_variables, unused_field

library;

import 'package:flutter/widgets.dart';

class NyIcons {
  NyIcons._();

  static const _kFontFam = 'NyIcons';
  static const String? _kFontPkg = null;

  static const IconData arrow_down = IconData(0xe800, fontFamily: _kFontFam);
  static const IconData arrow_left = IconData(0xe801, fontFamily: _kFontFam);
  static const IconData arrow_right = IconData(0xe802, fontFamily: _kFontFam);
  static const IconData arrow_up = IconData(0xe803, fontFamily: _kFontFam);
  static const IconData broccoli = IconData(0xe804, fontFamily: _kFontFam);
  static const IconData burger = IconData(0xe805, fontFamily: _kFontFam);
  static const IconData check = IconData(0xe806, fontFamily: _kFontFam);
  static const IconData chevron_down = IconData(0xe807, fontFamily: _kFontFam);
  static const IconData chevron_left = IconData(0xe808, fontFamily: _kFontFam);
  static const IconData chevron_right = IconData(0xe809, fontFamily: _kFontFam);
  static const IconData chevron_up = IconData(0xe80a, fontFamily: _kFontFam);
  static const IconData cross_filled = IconData(0xe80b, fontFamily: _kFontFam);
  static const IconData cross = IconData(0xe80c, fontFamily: _kFontFam);
  static const IconData dollar = IconData(0xe80d, fontFamily: _kFontFam);
  static const IconData edit = IconData(0xe80e, fontFamily: _kFontFam);
  static const IconData eye_off = IconData(0xe80f, fontFamily: _kFontFam);
  static const IconData eye = IconData(0xe810, fontFamily: _kFontFam);
  static const IconData gift = IconData(0xe811, fontFamily: _kFontFam);
  static const IconData headphone = IconData(0xe812, fontFamily: _kFontFam);
  static const IconData house = IconData(0xe813, fontFamily: _kFontFam);
  static const IconData human_go = IconData(0xe814, fontFamily: _kFontFam);
  static const IconData image = IconData(0xe815, fontFamily: _kFontFam);
  static const IconData info_i = IconData(0xe816, fontFamily: _kFontFam);
  static const IconData info = IconData(0xe817, fontFamily: _kFontFam);
  static const IconData lightning_off = IconData(0xe818, fontFamily: _kFontFam);
  static const IconData lightning = IconData(0xe819, fontFamily: _kFontFam);
  static const IconData like_filled = IconData(0xe81a, fontFamily: _kFontFam);
  static const IconData like_outlined = IconData(0xe81b, fontFamily: _kFontFam);
  static const IconData location = IconData(0xe81c, fontFamily: _kFontFam);
  static const IconData lock = IconData(0xe81d, fontFamily: _kFontFam);
  static const IconData minus = IconData(0xe81e, fontFamily: _kFontFam);
  static const IconData pepper = IconData(0xe81f, fontFamily: _kFontFam);
  static const IconData phone = IconData(0xe820, fontFamily: _kFontFam);
  static const IconData pin_grey_lg = IconData(0xe821, fontFamily: _kFontFam);
  static const IconData pin_grey_sm = IconData(0xe822, fontFamily: _kFontFam);
  static const IconData pin = IconData(0xe823, fontFamily: _kFontFam);
  static const IconData plus = IconData(0xe824, fontFamily: _kFontFam);
  static const IconData qr = IconData(0xe825, fontFamily: _kFontFam);
  static const IconData reboot = IconData(0xe826, fontFamily: _kFontFam);
  static const IconData restaurant_filled =
      IconData(0xe827, fontFamily: _kFontFam);
  static const IconData restaurant = IconData(0xe828, fontFamily: _kFontFam);
  static const IconData search = IconData(0xe829, fontFamily: _kFontFam);
  static const IconData share = IconData(0xe82a, fontFamily: _kFontFam);
  static const IconData star_filled = IconData(0xe82b, fontFamily: _kFontFam);
  static const IconData take_away = IconData(0xe82c, fontFamily: _kFontFam);
  static const IconData time = IconData(0xe82d, fontFamily: _kFontFam);
  static const IconData translation = IconData(0xe82e, fontFamily: _kFontFam);
  static const IconData trash = IconData(0xe82f, fontFamily: _kFontFam);
  static const IconData user = IconData(0xe830, fontFamily: _kFontFam);
  static const IconData veranda = IconData(0xe831, fontFamily: _kFontFam);
  static const IconData voucher_rectangle =
      IconData(0xe832, fontFamily: _kFontFam);
  static const IconData walk = IconData(0xe833, fontFamily: _kFontFam);
  static const IconData check_circle_filled =
      IconData(0xe834, fontFamily: _kFontFam);
  static const IconData danger_circle_filled =
      IconData(0xe835, fontFamily: _kFontFam);
  static const IconData warn_circle_filled =
      IconData(0xe836, fontFamily: _kFontFam);
  static const IconData warn_circle_outlined =
      IconData(0xe837, fontFamily: _kFontFam);
}
